WIP

diff --git a/.github/workflows/benchmark-core.yml b/.github/workflows/benchmark-core.yml
--- a/.github/workflows/benchmark-core.yml
+++ b/.github/workflows/benchmark-core.yml
@@ -69,3 +69,94 @@ jobs:
             yew-master/tools/output.log
             current-pr/tools/output.log
           retention-days: 1
+
+  post-benchmark-core:
+    name: Post Comment on Pull Request
+    runs-on: ubuntu-latest
+    needs: benchmark-core
+
+    steps:
+      - name: Download Repository
+        uses: actions/checkout@v3
+
+      - name: Download Artifact
+        uses: Legit-Labs/action-download-artifact@v2
+        with:
+          github_token: "${{ secrets.GITHUB_TOKEN }}"
+          workflow: benchmark-core.yml
+          run_id: ${{ github.event.workflow_run.id }}
+          name: benchmark-core
+          path: "benchmark-core/"
+
+      - name: Make pull request comment
+        run: |
+          cat - >>comment.txt <<EOF
+          ### Benchmark - core
+          #### Yew Master
+          ```
+          EOF
+          cat benchmark-core/yew-master/tools/output.json >>comment.txt
+          cat - >>comment.txt <<EOF
+          ```
+          #### Pull Request" >> comment.txt
+          ```
+          EOF
+          cat benchmark-core/current-pr/tools/output.json >>comment.txt
+          cat - >>comment.txt <<EOF
+          ```
+          EOF
+
+      - name: Read Pull Request ID
+        run: |
+          PR_NUMBER=$(cat "benchmark-core/.PR_NUMBER")
+          if ! [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
+            echo "pr number invalid"
+            exit 1
+          fi
+          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
+
+      - name: Post Comment
+        uses: actions/github-script@v6
+        with:
+          script: |
+            const fs = require('fs');
+
+            const commentInfo = {
+              ...context.repo,
+              issue_number: ${{ env.PR_NUMBER }},
+            };
+
+            const comment = {
+              ...commentInfo,
+              body: fs.readFileSync("comment.txt", 'utf-8'),
+            };
+
+            function isCommentByBot(comment) {
+              return comment.user.type === "Bot" && comment.body.includes("### Benchmark - core");
+            }
+
+            let commentId = null;
+            const comments = (await github.rest.issues.listComments(commentInfo)).data;
+            for (let i = comments.length; i--; ) {
+              const c = comments[i];
+              if (isCommentByBot(c)) {
+                commentId = c.id;
+                break;
+              }
+            }
+
+            if (commentId) {
+              try {
+                await github.rest.issues.updateComment({
+                  ...context.repo,
+                  comment_id: commentId,
+                  body: comment.body,
+                });
+              } catch (e) {
+                commentId = null;
+              }
+            }
+
+            if (!commentId) {
+              await github.rest.issues.createComment(comment);
+            }
