remove requirement for publish-env

diff --git a/.github/workflows/publish-website.yml b/.github/workflows/publish-website.yml
--- a/.github/workflows/publish-website.yml
+++ b/.github/workflows/publish-website.yml
@@ -8,22 +8,12 @@ on:
 jobs:
   publish:
     runs-on: ubuntu-latest
-    env:
-      PUBLISH_ENV_FILE: "PUBLISH_ENV"
     steps:
-      - name: Download publish env
-        uses: dawidd6/action-download-artifact@v2
-        with:
-          github_token: "${{ secrets.GITHUB_TOKEN }}"
-          workflow: build-website.yml
-          run_id: ${{ github.event.workflow_run.id }}
-          name: publish-env
-
-      - name: Apply publish env
+      - if: github.event.workflow_run.conclusion != 'success'
+        name: Abort if build failed
         run: |
-          echo "Publish env:"
-          cat "$PUBLISH_ENV_FILE"
-          cat "$PUBLISH_ENV_FILE" >> $GITHUB_ENV
+          echo "build failed"
+          exit 1
 
       - name: Download build artifact
         uses: dawidd6/action-download-artifact@v2
@@ -33,6 +23,18 @@ jobs:
           run_id: ${{ github.event.workflow_run.id }}
           name: website
           path: website/build/yew
+
+      - if: github.event.workflow_run.event == 'pull_request'
+        name: Apply pull request environment
+        run: |
+          echo "PR_NUMBER=${{ github.event.workflow_run.pull_requests[0].number }}" >> $GITHUB_ENV
+          echo "PR_BRANCH=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
+          echo "COMMIT_SHA=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV
+
+      - if: github.event.workflow_run.event == 'push'
+        name: Apply push environment
+        run: |
+          echo "CHANNEL_ID=live" >> $GITHUB_ENV
 
       # need to checkout to get "firebase.json", ".firebaserc"
       - uses: actions/checkout@v2
