pass pull request number (again)

diff --git a/.github/workflows/publish-website.yml b/.github/workflows/publish-website.yml
--- a/.github/workflows/publish-website.yml
+++ b/.github/workflows/publish-website.yml
@@ -8,6 +8,8 @@ on:
 jobs:
   publish:
     runs-on: ubuntu-latest
+    env:
+      PR_INFO_FILE: ".PR_INFO"
     steps:
       - if: github.event.workflow_run.conclusion != 'success'
         name: Abort if build failed
@@ -28,9 +30,23 @@ jobs:
           path: website/build/yew
 
       - if: github.event.workflow_run.event == 'pull_request'
+        name: Download pr info
+        uses: dawidd6/action-download-artifact@v2
+        with:
+          github_token: "${{ secrets.GITHUB_TOKEN }}"
+          workflow: build-website.yml
+          run_id: ${{ github.event.workflow_run.id }}
+          name: pr-info
+
+      - if: github.event.workflow_run.event == 'pull_request'
         name: Apply pull request environment
         run: |
-          echo "PR_NUMBER=${{ github.event.workflow_run.pull_requests[0].number }}" >> $GITHUB_ENV
+          pr_number=$(cat "$PR_INFO_FILE")
+          if ! [[ "$pr_number" =~ ^[0-9]+$ ]]; then
+            echo "pr number invalid"
+            exit 1
+          fi
+          echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
           echo "PR_BRANCH=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
           echo "COMMIT_SHA=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV
 
